### ISSUE TITLE
Practica 1 Mockup

### ISSUE THREAD

**Issue by Anakimberly** [SistemasTecTlaxiaco/actividad-1-practicaprototipo-equipo-j-a-k#2]
PROYECTO FIGMA:
https://www.figma.com/proto/CKOyLaKkKFDLMoUWfPYBnp/Proyecto?type=design&node-id=1-4&t=WdjkEH9ooN8rk60e-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A4
REPORTE:
https://drive.google.com/file/d/1C6WsBNX_rlrajEvmHF-KB3FuDun4rFIy/view?usp=drivesdk
integrantes:
Ana Kimberly Hernandez Perez 
Ameli Reyes Hernandez 
Jaczibeth Cruz Ramirez

**Comment by Ariadnamonserrat10** [comment]
96
Por qué tiene algunas fallas en la parte de explicación donde repiten unas palabras y en la descripción faltó ser un poco más específico.
Además de que en la conclusión dan mucho redondeo pero no aplican los resultados que obtuvieron ni que aprendieron.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
